version: '3.8'

networks:
    mynetwork:
      driver: bridge
services:
  web:
    build: .
    volumes:
      - ./:/code
    ports:
      - 80:80
    networks:
      - mynetwork
    depends_on:
      - elastic
  
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: my_elasticsearch
    environment:
      - node.name=my-node
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - mynetwork
  
  